import os
from supabase import create_client
from dotenv import load_dotenv

load_dotenv()
url = os.getenv("SUPABASE_URL")
key = os.getenv("SUPABASE_KEY")

def create_table():
    supabase = create_client(url, key)
    
    # SQL to create the table
    sql = """
    CREATE TABLE IF NOT EXISTS analysis_results (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        video_url TEXT,
        series_title TEXT,
        video_duration FLOAT,
        num_scenes INTEGER,
        average_shot_length FLOAT,
        pacing_score FLOAT,
        evaluation_label TEXT,
        evaluation_description TEXT,
        evaluation_color TEXT,
        scene_details JSONB,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        success BOOLEAN,
        error TEXT
    );
    
    -- Pour que les données soient visibles publiquement (selon ton besoin front)
    ALTER TABLE analysis_results ENABLE ROW LEVEL SECURITY;
    CREATE POLICY "Allow public read access" ON analysis_results FOR SELECT USING (true);
    CREATE POLICY "Allow service role insert" ON analysis_results FOR INSERT WITH CHECK (true);
    """
    
    print(f"Tentative de création de la table sur {url}...")
    try:
        # On utilise l'interface RPC pour exécuter du SQL si possible, 
        # sinon on informe qu'il faut le faire via le dashboard Supabase.
        # Note: 'exec_sql' est une fonction RPC commune mais pas standard.
        res = supabase.rpc("exec_sql", {"sql_query": sql}).execute()
        print("Commande envoyée avec succès.")
    except Exception as e:
        print(f"\n[!] Impossible de créer la table via l'API (souvent bloqué par défaut).")
        print(f"Action requise : Copie-colle le SQL suivant dans le 'SQL Editor' de ton Dashboard Supabase :\n")
        print(sql)

if __name__ == "__main__":
    create_table()
