lines = [
    "\"\"\"",
    "Script pour analyser les videos Dailymotion et les sauvegarder dans Supabase",
    "\"\"\"",
    "",
    "import os",
    "import sys",
    "import time",
    "from datetime import datetime",
    "from typing import Dict, Any, List, Optional",
    "",
    "# Ajouter les imports manquants",
    "import subprocess",
    "import tempfile",
    "",
    "# Fonction download_video_snippet",
    "def download_video_snippet(video_url: str, max_duration: int = 60, force_format: bool = False) -> Optional[str]:",
    "    \"\"\"Telecharge un extrait d'une video",
    "",
    "    Args:",
    "        video_url: URL de la video",
    "        max_duration: Duree maximale en secondes",
    "        force_format: Forcer un format different",
    "",
    "    Returns:",
    "        Chemin du fichier telecharge ou None",
    "    \"\"\"",
    "",
    "    # Creer un nom de fichier unique",
    "    temp_dir = tempfile.gettempdir()",
    "    video_id = video_url.split(\"/\")[-1]",
    "    output_path = os.path.join(temp_dir, f\"video_{video_id}.mp4\")",
    "",
    "    # Construire la commande yt-dlp avec gestion d'erreur",
    "    if force_format:",
    "        # Essayer avec liste de formats (plus permissif)",
    "        cmd = [\"yt-dlp\", \"--format\", \"best[height<=480]/best\", \"--output\", output_path, \"--impersonate\", \"Chrome-99\", \"--quiet\", \"--no-warnings\", \"--no-check-certificate\", video_url]",
    "    else:",
    "        # Format original",
    "        cmd = [\"yt-dlp\", \"--format\", \"bestvideo[height<=480][ext=mp4]/best[height<=480]\", \"--output\", output_path, \"--impersonate\", \"Chrome-99\", \"--quiet\", \"--no-warnings\", \"--no-check-certificate\", video_url]",
    "",
    "    try:",
    "        # Executer la commande",
    "        result = subprocess.run(cmd, check=True, capture_output=True, timeout=60)",
    "",
    "        # Verifier si le fichier existe",
    "        if os.path.exists(output_path) and os.path.getsize(output_path) > 0:",
    "            return output_path",
    "        else:",
    "            print(f\"   [ERROR] Fichier vide ou inexistant: {output_path}\")",
    "            return None",
    "",
    "    except subprocess.CalledProcessError as e:",
    "        print(f\"   [ERROR] Erreur yt-dlp: {e}\")",
    "        print(e.stderr.decode(\"utf-8\", errors=\"replace\"))",
    "        return None",
    "    except subprocess.TimeoutExpired:",
    "        print(f\"   [ERROR] Timeout yt-dlp\")",
    "        return None",
    "    except Exception as e:",
    "        print(f\"   [ERROR] Erreur inattendue: {e}\")",
    "        return None",
    "",
    "# Fonction analyze_video",
    "def analyze_video(video: Dict[str, Any]) -> Dict[str, Any]:",
    "    \"\"\"Analyse une video Dailymotion",
    "",
    "    Args:",
    "        video: Dictionnaire avec les informations de la video",
    "",
    "    Returns:",
    "        Dictionnaire avec les resultats",
    "    \"\"\"",
    "",
    "    video_url = f\"https://www.dailymotion.com/video/{video['id']}\"",
    "    series_title = video.get(\"series_title\")",
    "",
    "    print(f\"\\n[ANALYSE] {series_title}\")",
    "    print(f\"   URL: {video_url}\")",
    "",
    "    # Telecharger la video avec gestion d'erreur et retries",
    "    try:",
    "        print(\"   [DOWNLOAD] Telechargement...\")",
    "",
    "        video_path = None",
    "",
    "        # Essayer avec yt-dlp (format different)",
    "        try:",
    "            video_path = download_video_snippet(video_url, max_duration=60)",
    "            if video_path:",
    "                print(f\"   [OK] Video telechargee (yt-dlp): {video_path}\")",
    "        except Exception as e1:",
    "            print(f\"   [WARN] yt-dlp a echoue: {e1}\")",
    "            try:",
    "                print(\"   [RETRY] Essai autre format...\")",
    "                video_path = download_video_snippet(video_url, max_duration=60, force_format=True)",
    "                if video_path:",
    "                    print(f\"   [OK] Video telechargee (retry): {video_path}\")",
    "            except Exception as e2:",
    "                print(f\"   [ERROR] Telechargement echoue: {e2}\")",
    "                return {\"success\": False, \"error\": \"Echec telechargement (formats)\"}",
    "        ",
    "        if not video_path or not os.path.exists(video_path):",
    "            return {\"success\": False, \"error\": \"Echec telechargement (fichier)\"}",
    "",
    "        # Analyser la video",
    "        print(\"   [ANALYSIS] Analyse en cours...\")",
    "        try:",
    "            result = analyzer.analyze_video(video_path, analyze_motion=False, analyze_flashes=True)",
    "        except Exception as e:",
    "            print(f\"   [ERROR] Analyse echoue: {e}\")",
    "            return {\"success\": False, \"error\": \"Echec analyse\"}",
    "",
    "        # Nettoyer",
    "        if os.path.exists(video_path):",
    "            os.remove(video_path)",
    "",
    "        if not result.get(\"success\"):",
    "            return {\"success\": False, \"error\": \"Echec analyse\"}",
    "",
    "        # Ajouter des metadata",
    "        result[\"series_title\"] = series_title",
    "        result[\"video_url\"] = video_url",
    "        result[\"video_key\"] = video[\"id\"]",
    "        result[\"tmdb_id\"] = video.get(\"tmdb_id\")",
    "",
    "        return result",
    "",
    "    except Exception as e:",
    "        print(f\"   [ERROR] Erreur analyse: {e}\")",
    "        return {\"success\": False, \"error\": str(e)}",
    "",
    "# Fonction save_results_to_supabase (modifiee)",
    "def save_results_to_supabase(video_id: str, result: Dict[str, Any], video_url: str = None, series_title: str = None, video_key: str = None, tmdb_id: int = None) -> bool:",
    "    \"\"\"Sauvegarde les resultats dans analysis_results ET video_analyses\"\"\"",
    "    manager = SupabaseManager()",
    "",
    "    if not manager.client:",
    "        print(\"[ERROR] Supabase non configuree\")",
    "        return False",
    "",
    "    # 1. Mettre a jour la tache dans analysis_results",
    "    update_data = {",
    "        \"success\": result.get(\"success\", False),",
    "        \"video_duration\": result.get(\"video_duration\"),",
    "        \"num_scenes\": result.get(\"num_scenes\"),",
    "        \"average_shot_length\": result.get(\"average_shot_length\"),",
    "        \"pacing_score\": result.get(\"pacing_score\"),",
    "        \"evaluation_label\": result.get(\"evaluation\", {}).get(\"label\"),",
    "        \"evaluation_description\": result.get(\"evaluation\", {}).get(\"description\"),",
    "        \"evaluation_color\": result.get(\"evaluation\", {}).get(\"color\"),",
    "        \"scene_details\": result.get(\"scene_details\", []),",
    "    }",
    "",
    "    if result.get(\"error\"):",
    "        update_data[\"error\"] = result[\"error\"]",
    "",
    "    try:",
    "        response = manager.client.table(\"analysis_results\").update(update_data).eq(\"id\", video_id).execute()",
    "        print(f\"   [OK] Resultats mis a jour dans analysis_results\")",
    "    except Exception as e:",
    "        print(f\"   [ERROR] Erreur mise a jour analysis_results: {e}\")",
    "        return False",
    "",
    "    # 2. Si analyse reussie, inserer dans video_analyses (avec verification doublons)",
    "    if result.get(\"success\"):",
    "        success = manager.save_analysis_result(",
    "            result=result,",
    "            video_url=video_url or \"\",",
    "            series_title=series_title,",
    "            tmdb_id=tmdb_id,",
    "            video_key=video_key",
    "        )",
    "        if success:",
    "            print(f\"   [OK] Resultat sauvegarde dans video_analyses\")",
    "        else:",
    "            print(f\"   [WARN] Echec sauvegarde video_analyses (deja existant ?)\")",
    "",
    "    return True",
    "",
    "# Fonction main (modifiee)",
    "def main():",
    "    \"\"\"Fonction principale\"\"\"",
    "    print(\"=\" * 60)",
    "    print(\"[ANALYSE] VIDEOS DAILYMOTION - PacingScore Kids Protection\")",
    "    print(\"=\" * 60)",
    "",
    "    # Recuperer les videos a analyser",
    "    print(\"\\n[INFO] Recuperation des videos non analysees...\")",
    "    videos = get_videos_to_analyze()",
    "",
    "    if not videos:",
    "        print(\"[INFO] Aucune video a analyser (toutes sont deja analysees)\")",
    "        return",
    "",
    "    print(f\"[INFO] {len(videos)} videos a analyser\")",
    "",
    "    # Analyser chaque video",
    "    success_count = 0",
    "    for i, video in enumerate(videos, 1):",
    "        print(f\"\\n{'='*60}\")",
    "        print(f\"[INFO] Video {i}/{len(videos)}\")",
    "        print(f\"{'='*60}\")",
    "",
    "        # Analyser la video",
    "        result = analyze_video(video)",
    "",
    "        # Sauvegarder les resultats avec parametres supplementaires",
    "        video_url = video.get(\"video_url\")",
    "        series_title = video.get(\"series_title\")",
    "        video_key = video.get(\"video_key\")",
    "        tmdb_id = video.get(\"tmdb_id\")",
    "        if save_results_to_supabase(video[\"id\"], result, video_url=video_url, series_title=series_title, video_key=video_key, tmdb_id=tmdb_id):",
    "            success_count += 1",
    "            print(f\"[OK] Video {i} terminee avec succes\")",
    "        else:",
    "            print(f\"[ERROR] Video {i} echec sauvegarde\")",
    "",
    "        # Pause courte entre les videos",
    "        if i < len(videos):",
    "            print(\"   Pause de 2 secondes...\")",
    "            time.sleep(2)",
    "",
    "    print(f\"\\n{'='*60}\")",
    "    print(f\"[RESULT] RESULTATS FINAUX\")",
    "    print(f\"{'='*60}\")",
    "    print(f\"[OK] Videos analysees avec succes: {success_count}/{len(videos)}\")",
    "    print(f\"[INFO] Taux de succes: {(success_count/len(videos)*100):.1f}%\")",
    "",
    "    if success_count == len(videos):",
    "        print(\"\\n[SUCCESS] Toutes les videos ont ete analysees !\")",
    "    else:",
    "        print(f\"\\n[WARNING] {len(videos) - success_count} video(s) n'ont pas pu etre analysee(s)\")",
    "",
    "",
    "if __name__ == \"__main__\":",
    "    main()",
]

with open("analyze_dailymotion_videos_fixed.py", "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("Fichier corrigé créé avec succès !")
