CREATE TABLE IF NOT EXISTS analysis_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_url TEXT,
    series_title TEXT,
    video_duration FLOAT,
    num_scenes INTEGER,
    average_shot_length FLOAT,
    pacing_score FLOAT,
    evaluation_label TEXT,
    evaluation_description TEXT,
    evaluation_color TEXT,
    scene_details JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    success BOOLEAN,
    error TEXT,
    series_year INTEGER,
    series_overview TEXT,
    series_genres JSONB,
    scan_type TEXT,
    tmdb_id INTEGER UNIQUE,
    video_key TEXT UNIQUE
);

-- Pour que les données soient visibles publiquement (selon ton besoin front)
ALTER TABLE analysis_results ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON analysis_results FOR SELECT USING (true);
CREATE POLICY "Allow service role insert" ON analysis_results FOR INSERT WITH CHECK (true);
