# Backend Spring Boot API - Production
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jdk-jammy
WORKDIR /app

# Limiter la mémoire JVM
ENV JAVA_OPTS="-Xmx1g -Xms512m"

COPY --from=build /app/target/pacingscore-core-0.0.1-SNAPSHOT.jar app.jar
COPY entrypoint.sh .

RUN chmod +x entrypoint.sh

EXPOSE 8080

ENTRYPOINT ["./entrypoint.sh"]
